name: Bash

on:
  push:
    branches: [ dev ]

jobs:

  build:
    name: Build dev branch
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Check if .version file exists
      run: if [[ -f .version ]]; then exit 0; else exit 2; fi

    - name: Read out .version file
      id: readversionfile
      run: echo "::set-output name=desiredversion::$(cat .version)"

    - name: Verify version
      run: echo "${{steps.readversionfile.outputs.desiredversion}}"

    - name: Lookup planned tag
      id: tagexists
      run: |
        echo "::set-output name=tagexists::$(curl -s -X GET -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --url https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{steps.readversionfile.outputs.desiredversion}} | jq .object.sha)"
    
    - name: Check if planned tag doesn't exist yet
      run: if [[ "${{ steps.tagexists.outputs.tagexists }}" == "null" ]]; then exit 0; else exit 2; fi

    - name: Build
      run: make build

    - name: Generate changelog
      id: genchangelog
      shell: bash
      run: |
        echo "Checking tags..."
        git tag
        current_tag=$(git tag | tail -1)
        changelog_filename=".changelog"
        echo "current_tag=$current_tag"

        echo "Listing all changes..."
        git log --format=%B

        echo "Listing current changes..."
        git log --format=%B "$current_tag"..HEAD | tee "$changelog_filename"
        
        echo "Changelog file..."
        cat .changelog
        echo "::set-output name=changelog::$(cat "$changelog_filename")"

