name: Bash

on:
  push:
    branches: [ dev ]

jobs:

  build:
    name: Build dev branch
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if .version file exists
      run: if [[ -f .version ]]; then exit 0; else exit 2; fi

    - name: Read out .version file
      id: readversionfile
      run: echo "::set-output name=desiredversion::$(cat .version)"

    - name: Verify version
      run: echo "${{steps.readversionfile.outputs.desiredversion}}"

    - name: Lookup planned tag
      id: tagexists
      run: |
        echo "::set-output name=tagexists::$(curl -s -X GET -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --url https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{steps.readversionfile.outputs.desiredversion}} | jq .object.sha)"
    
    - name: Check if planned tag doesn't exist yet
      run: if [[ "${{ steps.tagexists.outputs.tagexists }}" == "null" ]]; then exit 0; else exit 2; fi

    - name: Build
      run: make build

    - name: Generate changelog
      id: genchangelog
      shell: bash
      run: |
        echo "Checking tags..."
        git branch
        git tag
        git describe --tags
        
        described=$(git describe --tags)
        described_parts=( ${described//-/ } )
        current_tag=${described_parts[0]}
        
        changelog_filename=".changelog"
        echo "current_tag=${current_tag}"

        echo "Listing all changes..."
        git log --format=%B | sort -u

        echo "Listing current changes..."
        git log --format=%B "$current_tag"..HEAD | sort -u | tee "${changelog_filename}"
        
        echo "Changelog file..."
        cat .changelog
        echo "::set-output name=changelog::$(cat "${changelog_filename}")"

    - name: Display changelog
      run: echo "${{ steps.genchangelog.outputs.changelog }}"

    - name: Setup RPM Build environment
      id: setuprpmbuildenv
      shell: bash
      run: |
        set +e

        version="$(cat .version)"
        sudo apt-get update
        sudo apt-get install rpm

        make build
        make compress

        # rpmdev-setuptree
        mkdir /home/runner/rpmbuild
        mkdir -pv /home/runner/rpmbuild/BUILD
        mkdir -pv /home/runner/rpmbuild/BUILDROOT
        mkdir -pv /home/runner/rpmbuild/RPMS
        mkdir -pv /home/runner/rpmbuild/SOURCES
        mkdir -pv /home/runner/rpmbuild/SPECS
        mkdir -pv /home/runner/rpmbuild/SRPMS
        
        ls -la
        
        cp -v "postfix_bexporter.spec.tpl" /home/runner/rpmbuild/SPECS
        mv -v /home/runner/rpmbuild/SPECS/postfix_bexporter.spec.tpl /home/runner/rpmbuild/SPECS/postfix_bexporter.spec
        
        sed -i"" \
          -e "s/__VERSION__/${version}/" \
          -e "s/__SOURCE_TARGZ_FILENAME__/postfix_bexporter-${version}.tar.gz/" \
          /home/runner/rpmbuild/SPECS/postfix_bexporter.spec
        
        cat .changelog >> /home/runner/rpmbuild/SPECS/postfix_bexporter.spec
        cat -n /home/runner/rpmbuild/SPECS/postfix_bexporter.spec

        cp -v "postfix_bexporter-${version}.tar.gz" /home/runner/rpmbuild/SOURCES

        pwd
        ls -la /home/runner/rpmbuild/SOURCES/postfix_bexporter-1.0.2.tar.gz

        cd /home/runner
        rpmbuild -vba "rpmbuild/SPECS/postfix_bexporter.spec"
